spring:
   datasource:
      driverClassName: org.h2.Driver
      password: ''
      url: jdbc:h2:mem:rota2010
      username: sa
      
   h2:
      console:
         enabled: true
         path: /h2-console
         
   jpa:
      database-plataform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
         format_sql: true
         ddl-auto: update
                  
   rabbitmq:
      request:
         host: localhost
         port: 5672
         username: guest
         password: guest
         exchange:
            producer: ex.producer.rota2030
         routing-key:
            producer: rk.producer.rota2030
         deadletter:
            producer: dl.producer.rota203000