INSERT INTO GRUPO(GRUPO_ID,GRUPO_DESCRICAO) VALUES(1,'Grupo A');
INSERT INTO GRUPO(GRUPO_ID,GRUPO_DESCRICAO) VALUES(2,'Grupo B');
INSERT INTO GRUPO(GRUPO_ID,GRUPO_DESCRICAO) VALUES(3,'Grupo C');

INSERT INTO TIPO(TIPO_ID,TIPO_DESCRICAO) VALUES(1,'Automovel');
INSERT INTO TIPO(TIPO_ID,TIPO_DESCRICAO) VALUES(2,'Caminhonete');
INSERT INTO TIPO(TIPO_ID,TIPO_DESCRICAO) VALUES(3,'Utilitario');

INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item W', 'Norma W', true, 1, 1);

INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item X', 'Norma X', true, 1, 1);

INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item Y', 'Norma Y', false, 2, 2);
							  
INSERT INTO ITEM_DE_SEGURANCA(ITEM_DE_SEGURANCA_DESCRICAO,
							  ITEM_DE_SEGURANCA_NORMA_CONTRAM,
							  ITEM_DE_SEGURANCA_OBRIGATORIO,
							  GRUPO_ID,
							  TIPO_ID) VALUES('Item Z', 'Norma Z', 	true, 3, 3);
							  
